name: Discord Webhook for Dev Branch

on:
  release:
    types: [published]
jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook for Release (Embed Release Info)
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"ğŸ‰ **New Release Published!**\nğŸ“‚ **Repo:** <https://github.com/${{ github.repository }}>\nğŸ· **Release:** [${{ github.event.release.tag_name }}](https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }})\nğŸ“ **Notes:** ${{ github.event.release.name }}\"}" \
          $DISCORD_WEBHOOK_URL
