name: Discord Webhook for Dev Branch

on:
  push:
    branches:
      - master  # Only triggers on dev branch

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"**Push to Dev Branch!**\n **Repo:** <https://github.com/${{ github.repository }}>\n **Pusher:** <https://github.com/${{ github.actor }}>\n [Commit: $SHORT_SHA](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\"}" \
          $DISCORD_WEBHOOK_URL
